language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node-modules"
services:
  - postgresql
before_script:
  - psql -c 'create database politico_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
after_success: 
  - npm run coverage
  